/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class TestingTimer {
  constructor()
  advance(tick: number): void
}

export declare class TimingWheel {
  constructor()
  static withTesting(test: TestingTimer): TimingWheel
  setRef(id: number): void
  clearRef(id: number): void
  isRefEmpty(): boolean
  hasRef(id: number): boolean
  get length(): number
  isEmpty(): boolean
  refresh(id: number): void
  register(delay: number, callback: VoidCallback, isInterval: boolean): number
  unregister(id: number): void
  tick(): void
}

export type VoidCallback =
  () => void
