/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class TestingTimer {
  startedAt: number
  tick: number
  constructor()
  advance(tick: number): void
}

export declare class TimingWheel {
  constructor()
  static withTesting(test: TestingTimer): TimingWheel
  setRef(id: number): void
  clearRef(id: number): void
  isRefEmpty(): boolean
  hasRef(id: number): boolean
  get length(): number
  isEmpty(): boolean
  refresh(id: number): void
  register(id: number, delay: number, callback: () => void, isInterval: boolean): void
  unregister(id: number): void
  tick(): void
}
